export enum EventTypes {
  Connected = "connected",
  Disconnected = "disconnected",
  GoToLogin = "login",
  KeyDown = "key-down",
  GoToRegisterNewUser = "register-new-user",
  Automate = "send-blank",
  SocketEmit = "socket-emit",
  ClearParser = "clear-parser",
  PrintParser = "print-parser",
  LoginDetected = "login-detected",
  LoggedInDetected = "logged-in-detected",
  LoggedOutDetected = "logged-out-detected",
  Play = "play",
  ReceivedData = "received-data",
  ReceivedInstructions = "received-instructions",
  PlayDetected = "play-detected",
}
